title: Malicious AppX Package Installed
id: 09d3b48b-be17-47f5-bf4e-94e7e75d09ce
status: experimental
description: Detects installation of known malicious appx packages
references:
    - https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
author: Nasreddine Bencherchali
date: 2023/01/11
tags:
    - attack.defense_evasion
logsource:
    product: windows
    service: appxdeployment-server
detection:
    selection:
        EventID: 401
        # Add more malicious package names
        PackageFullName|contains: '3669e262-ec02-4e9d-bcb4-3d008b4afac9_96.0.1072.0_'
    condition: selection
falsepositives:
    - Rare occasions where a malicious package uses the exact same name and version as a legtimate application
level: medium
