title: Microsoft 365 Rules
order: 10
ThreatManagement:
   product: m365
   category: ThreatManagement
   conditions:
       eventSource: SecurityComplianceCenter
AccessGovernance:
   product: m365
   category: AccessGovernance
   conditions:
       eventSource: SecurityComplianceCenter
