title: Splunk Windows log source conditions
order: 20
backends:
  - splunk
  - carbonblack
  - sumologic

fieldmappings:
  Image: path
  CurrentDirectory: path
  SourceIp: ipaddr
  ImageLoaded: modload
  CommandLine: cmdline
  DestinationIp: ipaddr
  DestinationAddress: ipaddr
  DestinationPort: ipport
  DestPort: ipport
  TargetObject: regmod
  TargetFilename: filemod
  ParentImage: parent_name
  SourceImage: parent_name
  TargetImage: childproc_name
  Description: file_desc
  Product: product_name
  Signature: digsig_publisher
  CallTrace: modload
  DestinationHostname: domain
  