title: Splunk Windows log source conditions
order: 20
backends:
  - splunk
  - carbonblack

fieldmappings:
  Image: path
  SourceIp: ipaddr
  ImageLoaded: modload
  CommandLine: cmdline
  DestinationIp: ipaddr