title: Splunk Windows log source conditions
order: 20
backends:
  - splunk
  - carbonblack
  - sumologic

fieldmappings:
  Image: path
  CurrentDirectory: path
  SourceIp: ipaddr
  ImageLoaded: modload
  CommandLine: cmdline
  DestinationIp: ipaddr
  DestinationAddress: ipaddr