title: Elastic Common Schema And Elastic Exported Fields Mapping For Okta logs
order: 20
backends:
  - es-qs
  - es-dsl
  - es-rule
  - kibana
  - kibana-ndjson
  - xpack-watcher
  - elastalert
  - elastalert-dsl
fieldmappings:
  ClientIp: okta.client.ip
  UserAgentRawUserAgent: okta.client.user_agent.raw_user_agent
  UserAgentOs: okta.client.user_agent.os
  UserAgentBrowser: okta.client.user_agent.browser
  ClientZone: okta.client.zone
  ClientDevice: okta.client.device
  ClientId: okta.client.id
  OutcomeReason: okta.outcome.reason
  OutcomeResult: okta.event.outcome
  Target: okta.target
  TransactionId: okta.transaction.id
  TransactionType: okta.transaction.type
  DeviceFingerprint: okta.debug_context.debug_data.device_fingerprint
  RequestId: okta.debug_context.debug_data.request_id
  RequestUri: okta.debug_context.debug_data.request_uri
  ThreatSuspected: okta.debug_context.debug_data.threat_suspected
  Url: okta.debug_context.debug_data.url
  SuspiciousActivityBrowser: okta.debug_context.debug_data.suspicious_activity.browser
  SuspiciousActivityEventCity : okta.debug_context.debug_data.suspicious_activity.event_city
  SuspiciousActivityEventCountry : okta.debug_context.debug_data.suspicious_activity.event_country
  SuspiciousActivityEventId : okta.debug_context.debug_data.suspicious_activity.event_id
  SuspiciousActivityEventIp : okta.debug_context.debug_data.suspicious_activity.event_ip
  SuspiciousActivityEventLatitude : okta.debug_context.debug_data.suspicious_activity.event_latitude
  SuspiciousActivityEventLongitude : okta.debug_context.debug_data.suspicious_activity.event_longitude
  SuspiciousActivityEventState : okta.debug_context.debug_data.suspicious_activity.event_state
  SuspiciousActivityEventTransactionId : okta.debug_context.debug_data.suspicious_activity.event_transaction_id
  SuspiciousActivityEventType : okta.debug_context.debug_data.suspicious_activity.event_type
  SuspiciousActivityEventOs : okta.debug_context.debug_data.suspicious_activity.os
  SuspiciousActivityEventTimestamp : okta.debug_context.debug_data.suspicious_activity.timestamp
  AuthenticationProvider: okta.authentication_context.authentication_provider
  AuthenticationCredentialProvider: okta.authentication_context.credential_provider
  AuthenticationCredentialType: okta.authentication_context.credential_type
  AuthenticationIssuer: okta.authentication_context.issuer
  AuthenticationExternalSessionID: okta.authentication_context.external_session_id
  AuthenticationInterface: okta.authentication_context.interface
