title: Elastic Common Schema And Elastic Exported Fields Mapping For Okta logs
order: 20
backends:
  - es-qs
  - es-dsl
  - es-rule
  - kibana
  - kibana-ndjson
  - xpack-watcher
  - elastalert
  - elastalert-dsl
fieldmappings:
  : okta.actor.id
  : okta.actor.type
  : okta.actor.alternate_id
  : okta.actor.display_name
  : okta.client.ip
  : okta.client.user_agent.raw_user_agent
  : okta.client.user_agent.os
  : okta.client.user_agent.browser
  : okta.client.zone
  : okta.client.device
  : okta.client.id
  : okta.outcome.reason
  : event.outcome
  : okta.target
  : okta.transaction.id
  : okta.transaction.type
  : okta.debug_context.debug_data.device_fingerprint
  : okta.debug_context.debug_data.request_id
  : okta.debug_context.debug_data.request_uri
  : okta.debug_context.debug_data.threat_suspected
  : okta.debug_context.debug_data.url
  : okta.debug_context.debug_data.suspicious_activity.browser
  : okta.debug_context.debug_data.suspicious_activity.event_city
  : okta.debug_context.debug_data.suspicious_activity.event_country
  : okta.debug_context.debug_data.suspicious_activity.event_id
  : okta.debug_context.debug_data.suspicious_activity.event_ip
  : okta.debug_context.debug_data.suspicious_activity.event_latitude
  : okta.debug_context.debug_data.suspicious_activity.event_longitude
  : okta.debug_context.debug_data.suspicious_activity.event_state
  : okta.debug_context.debug_data.suspicious_activity.event_transaction_id
  : okta.debug_context.debug_data.suspicious_activity.event_type
  : okta.debug_context.debug_data.suspicious_activity.os
  : okta.debug_context.debug_data.suspicious_activity.timestamp
  : okta.authentication_context.authentication_provider
  : okta.authentication_context.authentication_step
  : okta.authentication_context.credential_provider
  : okta.authentication_context.credential_type
  : okta.authentication_context.issuer
  : okta.authentication_context.external_session_id
  : okta.authentication_context.interface
  : okta.security_context.as.number
  : okta.security_context.as.organization.name
  : okta.security_context.isp
  : okta.security_context.domain
  : okta.security_context.is_proxy
  : okta.request.ip_chain.ip
  : okta.request.ip_chain.version
  : okta.request.ip_chain.source
  : okta.request.ip_chain.geographical_context.city
  : okta.request.ip_chain.geographical_context.state
  : okta.request.ip_chain.geographical_context.postal_code
  : okta.request.ip_chain.geographical_context.country
  : okta.request.ip_chain.geographical_context.geolocation
