title: uberAgent configuration
order: 20
backends:
  - uberagent
exclusion:
  - e6ce8457-68b1-485b-9bdd-3c2b5d679aa9 # 'VBA DLL Loaded Via Microsoft Word': Rule already included in default configuration.
  - a457f232-7df9-491d-898f-b5aabd2cbe2f # 'Windows Management Instrumentation DLL Loaded Via Microsoft Word': Rule already included in default configuration.
  - 295a59c1-7b79-4b47-a930-df12c15fc9c2 # 'Windows Registry Trust Record Modification': Rule already included in default configuration.