title: Elastic Winlogbeat (from 7.x) index pattern and field mapping following Elastic enabled Modules
order: 20
backends:
  - es-qs
  - es-dsl
  - es-rule
  - es-rule-eql
  - es-eql
  - kibana
  - kibana-ndjson
  - xpack-watcher
  - elastalert
  - elastalert-dsl
  - elasticsearch-rule
  - ee-outliers
logsources:
  windows:
    product: windows
    index: winlogbeat-*
  windows-application:
    product: windows
    service: application
    conditions:
      winlog.channel: Application
  windows-security:
    product: windows
    service: security
    conditions:
      winlog.channel: Security
  windows-system:
    product: windows
    service: system
    conditions:
      winlog.channel: System
  windows-sysmon:
    product: windows
    service: sysmon
    conditions:
      winlog.channel: 'Microsoft-Windows-Sysmon/Operational'
  windows-powershell:
    product: windows
    service: powershell
    conditions:
      winlog.channel: 'Microsoft-Windows-PowerShell/Operational'
  windows-classicpowershell:
    product: windows
    service: powershell-classic
    conditions:
      winlog.channel: 'Windows PowerShell'
  windows-dns-server:
    product: windows
    service: dns-server
    conditions:
      winlog.channel: 'DNS Server'
  windows-driver-framework:
    product: windows
    service: driver-framework
    conditions:
      winlog.provider_name: 'Microsoft-Windows-DriverFrameworks-UserMode/Operational'
  windows-dhcp:
    product: windows
    service: dhcp
    conditions:
      winlog.provider_name: 'Microsoft-Windows-DHCP-Server/Operational'
  windows-ntlm:
    product: windows
    service: ntlm
    conditions:
      winlog.provider_name: 'Microsoft-Windows-NTLM/Operational'
  windows-defender:
    product: windows
    service: windefend
    conditions:
      winlog.channel: 'Microsoft-Windows-Windows Defender/Operational'
  windows-printservice-admin:
    product: windows
    service: printservice-admin
    conditions:
      winlog.channel: 'Microsoft-Windows-PrintService/Admin'
  windows-printservice-operational:
    product: windows
    service: printservice-operational
    conditions:
      winlog.channel: 'Microsoft-Windows-PrintService/Operational'
  windows-smbclient-security:
    product: windows
    service: smbclient-security
    conditions:
      winlog.channel: 'Microsoft-Windows-SmbClient/Security'
  windows-applocker:
    product: windows
    service: applocker
    conditions:
      winlog.channel:
        - 'Microsoft-Windows-AppLocker/MSI and Script'
        - 'Microsoft-Windows-AppLocker/EXE and DLL'
        - 'Microsoft-Windows-AppLocker/Packaged app-Deployment'
        - 'Microsoft-Windows-AppLocker/Packaged app-Execution'
  windows-msexchange-management:
    product: windows
    service: msexchange-management
    conditions:
      winlog.channel: 'MSExchange Management'
defaultindex: winlogbeat-*
# Extract all field names with yq:
# yq -r '.detection | del(.condition) | map(keys) | .[][]' $(find sigma/rules/windows -name '*.yml') | sort -u | grep -v ^EventID$ | sed 's/^\(.*\)/    \1: winlog.event_data.\1/g'
# Keep EventID! Clean up the list afterwards!
fieldmappings:
    EventID: event.code
    Channel: winlog.channel
    AccessMask: winlog.event_data.AccessMask
    AccountName: winlog.event_data.AccountName
    AllowedToDelegateTo: winlog.event_data.AllowedToDelegateTo
    AttributeLDAPDisplayName: winlog.event_data.AttributeLDAPDisplayName
    AuditPolicyChanges: winlog.event_data.AuditPolicyChanges
    CallingProcessName: winlog.event_data.CallingProcessName
    ComputerName: winlog.ComputerName
    EventType: winlog.event_data.EventType
    FailureCode: winlog.event_data.FailureCode
    FileName: file.path
    HiveName: winlog.event_data.HiveName
    NewProcessName: winlog.event_data.NewProcessName
    ObjectClass: winlog.event_data.ObjectClass
    ObjectName: winlog.event_data.ObjectName
    ObjectType: winlog.event_data.ObjectType
    ObjectValueName: winlog.event_data.ObjectValueName
    ParentProcessName: process.parent.name
    Path: winlog.event_data.Path
    ProcessCommandLine: winlog.event_data.ProcessCommandLine
    Properties: winlog.event_data.Properties
    SecurityID: winlog.event_data.SecurityID
    ServiceFileName: winlog.event_data.ServiceFileName
    ShareName: winlog.event_data.ShareName
    Source: winlog.event_data.Source
    Status: winlog.event_data.Status
    TicketEncryptionType: winlog.event_data.TicketEncryptionType
    TicketOptions: winlog.event_data.TicketOptions
    TargetDomainName: user.domain
    TargetUserName: user.name
    TargetUserSid: user.id
    # Channel: WLAN-Autoconfig AND EventID: 8001
    AuthenticationAlgorithm: winlog.event_data.AuthenticationAlgorithm
    BSSID: winlog.event_data.BSSID
    BSSType: winlog.event_data.BSSType
    CipherAlgorithm: winlog.event_data.CipherAlgorithm
    ConnectionId: winlog.event_data.ConnectionId
    ConnectionMode: winlog.event_data.ConnectionMode
    InterfaceDescription: winlog.event_data.InterfaceDescription
    InterfaceGuid: winlog.event_data.InterfaceGuid
    OnexEnabled: winlog.event_data.OnexEnabled
    PHYType: winlog.event_data.PHYType
    ProfileName: winlog.event_data.ProfileName
    SSID: winlog.event_data.SSID
    #  from here missing field at 20210706
    Accesses: winlog.event_data.Accesses
    AccessList: winlog.event_data.AccessList
    AttributeValue: winlog.event_data.AttributeValue
    AuditSourceName: winlog.event_data.AuditSourceName
    CallerProcessName: winlog.event_data.CallerProcessName
    ClassName: winlog.event_data.ClassName
    ClassId: winlog.event_data.ClassId
    DestAddress: winlog.event_data.DestAddress
    DestPort: destination.port
    DeviceDescription: winlog.event_data.DeviceDescription
    # DeviceName =>  Microsoft-Windows-Ntfs  EventID: 98
    DeviceName: winlog.event_data.DeviceName
    # ErrorCode =>  printservice-admin  EventID: 4909 or 808
    ErrorCode: winlog.event_data.ErrorCode 
    FilePath: winlog.event_data.FilePath
    # Filename =>  product: antivirus
    Filename: winlog.event_data.Filename    
    LayerRTID: winlog.event_data.LayerRTID
    LDAPDisplayName: winlog.event_data.LDAPDisplayName
    # Level => Source: MSExchange Control Panel EventID: 4
    Level: winlog.event_data.Level
    NewValue: winlog.event_data.NewValue
    ObjectServer: winlog.event_data.ObjectServer
    PasswordLastSet: winlog.event_data.PasswordLastSet
    PrivilegeList: winlog.event_data.PrivilegeList
    RelativeTargetName: winlog.event_data.RelativeTargetName
    SamAccountName: winlog.event_data.SamAccountName
    Service: winlog.event_data.Service
    ServicePrincipalNames: winlog.event_data.ServicePrincipalNames
    SidHistory: winlog.event_data.SidHistory
    SourceAddress: source.ip
    TargetProcessAddress: winlog.event_data.TargetProcessAddress
    TargetServerName: winglog.event_data.TargetServerName
    TaskName: winlog.event_data.TaskName
    # UserName => smbclient-security  eventid:31017
    UserName: winlog.event_data.UserName
    Workstation: winlog.event_data.Workstation
    #
    # Sysmon/Operational up to ID 25
    #
    RuleName: winlog.event_data.RuleName
    ProcessGuid: process.entity_id
    ProcessId: process.pid
    Image: process.executable
    FileVersion: 
        category=process_creation: process.pe.file_version
        category=image_load: process.pe.file_version
        default: winlog.event_data.FileVersion
    Description:
        category=process_creation: process.pe.description
        category=image_load: process.pe.description
        category=sysmon_error: winlog.event_data.Description
        default: winlog.event_data.Description
    Product:
        category=process_creation: process.pe.product
        category=image_load: process.pe.product
        default: winlog.event_data.Product
    Company: 
        category=process_creation: process.pe.company
        category=image_load: process.pe.company
        default: winlog.event_data.Company
    OriginalFileName: process.pe.original_file_name
    CommandLine: 
        category=process_creation: process.command_line
        service=powershell-classic: powershell.command.value
        default: winlog.event_data.CommandLine
    CurrentDirectory: process.working_directory
    LogonGuid: winlog.event_data.LogonGuid
    LogonId: winlog.event_data.LogonId
    TerminalSessionId: winlog.event_data.TerminalSessionId
    IntegrityLevel: winlog.event_data.IntegrityLevel
    ParentProcessGuid: process.parent.entity_id
    ParentProcessId: process.parent.pid
    ParentImage: process.parent.executable
    ParentCommandLine: process.parent.command_line
    TargetFilename: file.path
    CreationUtcTime: winlog.event_data.CreationUtcTime
    PreviousCreationUtcTime: winlog.event_data.PreviousCreationUtcTime
    Protocol: network.transport
    Initiated: 
        category=network_connection: network.direction
        default: winlog.event_data.Initiated
    #SourceIsIpv6: winlog.event_data.SourceIsIpv6 #=gets deleted and not boolean...https://github.com/elastic/beats/blob/71eee76e7cfb8d5b18dfacad64864370ddb14ce7/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js#L278-L279
    SourceIp: source.ip
    SourceHostname: source.domain
    SourcePort: source.port
    SourcePortName: winlog.event_data.SourcePortName
    #DestinationIsIpv6: winlog.event_data.DestinationIsIpv6 #=gets deleted and not boolean...https://github.com/elastic/beats/blob/71eee76e7cfb8d5b18dfacad64864370ddb14ce7/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js#L278-L279
    DestinationIp: destination.ip
    DestinationHostname: destination.domain
    DestinationPort: destination.port
    DestinationPortName: network.protocol
    State: winlog.event_data.State
    Version: winlog.event_data.Version
    SchemaVersion: winlog.event_data.SchemaVersion
    ImageLoaded: file.path
    Signed: file.code_signature.signed
    Signature: file.code_signature.subject_name
    SignatureStatus: file.code_signature.status
    SourceProcessGuid: process.entity_id
    SourceProcessId: process.pid
    SourceImage: process.executable
    TargetProcessGuid: winlog.event_data.TargetProcessGuid
    TargetProcessId: winlog.event_data.TargetProcessId
    TargetImage: winlog.event_data.TargetImage
    NewThreadId: winlog.event_data.NewThreadId
    StartAddress: winlog.event_data.StartAddress
    StartModule: winlog.event_data.StartModule
    StartFunction: winlog.event_data.StartFunction
    Device: file.path
    SourceThreadId: process.thread.id
    GrantedAccess: winlog.event_data.GrantedAccess
    CallTrace: winlog.event_data.CallTrace
    TargetObject: registry.path
    Details: winlog.event_data.Details
    NewName: winlog.event_data.NewName
    Configuration: winlog.event_data.Configuration
    ConfigurationFileHash: winlog.event_data.ConfigurationFileHash
    PipeName: file.name
    User: winlog.event_data.User
    EventNamespace: winlog.event_data.EventNamespace
    Name: winlog.event_data.Name
    Query: winlog.event_data.Query
    Operation: winlog.event_data.Operation
    Type: winlog.event_data.Type
    Destination: process.executable
    Consumer: winlog.event_data.Consumer
    Filter: winlog.event_data.Filter
    QueryName: dns.question.name
    QueryStatus: sysmon.dns.status
    QueryResults: winlog.event_data.QueryResults
    IsExecutable: sysmon.file.is_executable
    Archived: sysmon.file.archived
    Session: winlog.event_data.Session
    ClientInfo: winlog.event_data.ClientInfo
    # SYSMON Hashes
    Hashes: winlog.event_data.Hashes
    # extraction from Hashes NOT a original field but find in some rule
    md5:
        category=driver_load: hash.md5
        category=image_load: file.hash.md5
        default: process.hash.md5
    sha1:
        category=driver_load: hash.sha1
        category=image_load: file.hash.sha1
        default: process.hash.sha1
    sha256:
        category=driver_load: hash.sha256
        category=image_load: file.hash.sha256
        default: process.hash.sha256
    Imphash: 
        category=driver_load: hash.imphash
        category=image_load: file.hash.imphash
        default: process.pe.imphash
    #
    # Powershell
    #
    CommandName: powershell.command.name
    CommandPath: powershell.command.path
    CommandType: powershell.command.type
    EngineVersion: 
        service=powershell-classic: powershell.engine.version
        default: winlog.event_data.EngineVersion
    HostApplication: process.command_line
    HostId: process.entity_id
    HostName: process.title
    HostVersion:
        service=powershell-classic: powershell.process.executable_version
        default: winlog.event_data.HostVersion
    NewEngineState: powershell.engine.new_state
    PipelineId: powershell.pipeline_id
    PreviousEngineState: powershell.engine.previous_state
    RunspaceId: powershell.runspace_id
    ScriptName: file.path
    SequenceNumber: event.sequence
    NewProviderState: powershell.provider.new_state
    ProviderName: powershell.provider.name
    Payload: winlog.event_data.Payload
    ContextInfo: winlog.event_data.ContextInfo
    MessageNumber: powershell.sequence
    MessageTotal: powershell.total
    ScriptBlockText: powershell.file.script_block_text
    ScriptBlockId: powershell.file.script_block_id
    #
    # Security
    #
    SubjectUserSid: user.id
    SubjectUserName: user.name
    SubjectDomainName: user.domain
    SubjectLogonId:
        service=security: winlog.logon.id
        default: winlog.event_data.SubjectLogonId
    #EventID 4610
    AuthenticationPackageName: winlog.event_data.AuthenticationPackageName
    #EventID 4611
    LogonProcessName: winlog.event_data.LogonProcessName
    #EventID 4616
    PreviousTime: winlog.event_data.PreviousTime
    NewTime: winlog.event_data.NewTime
    #EventID 4624
    TargetLogonId: 
        service=security: winlog.logon.id
        default: winlog.event_data.TargetLogonId
    LogonType: winlog.event_data.LogonType
    WorkstationName: source.domain
    TransmittedServices: winlog.event_data.TransmittedServices
    LmPackageName: winlog.event_data.LmPackageName
    KeyLength: winlog.event_data.KeyLength
    ProcessName: process.executable
    IpAddress: source.ip
    IpPort: source.port
    ImpersonationLevel: winlog.event_data.ImpersonationLevel
    RestrictedAdminMode: winlog.event_data.RestrictedAdminMode
    TargetOutboundUserName: winlog.event_data.TargetOutboundUserName
    TargetOutboundDomainName: winlog.event_data.TargetOutboundDomainName
    VirtualAccount: winlog.event_data.VirtualAccount
    TargetLinkedLogonId: winlog.event_data.TargetLinkedLogonId
    ElevatedToken: winlog.event_data.ElevatedToken
    #EventID 7045
    ServiceName:
        service=security: service.name
        default: winlog.event_data.ServiceName
    ImagePath: winlog.event_data.ImagePath
    ServiceType: winlog.event_data.ServiceType
    StartType: winlog.event_data.ServiceStartType
