title: Sysmon Configuration Change
id: 8ac03a65-6c84-4116-acad-dc1558ff7a77
description: Someone can try to hide from Sysmon
status: experimental
author: frack113
date: 2022/01/12
references:
    - https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon
logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 16
    condition: selection
falsepositives:
    - legitimate administrative action
level: medium 
tags:
    - attack.defense_evasion
