title: Auditing configuration changes on linux host
description: Detect changes if auditd configuration files
    # Example config for this one (place it at the top of audit.rules)
    # -w /etc/audit/ -p wa -k etc_modify_auditconfig
    # -w /etc/libaudit.conf -p wa -k etc_modify_libauditconfig
    # -w /etc/audisp/ -p wa -k etc_modify_audispconfig
references:
    - https://github.com/Neo23x0/auditd/blob/master/audit.rules
    - self experience
tags:
    - attack.defense_evasion
    - attack.t1054
author: Mikhail Larin, oscd.community
status: experimental
date: 2019/10/25
logsource:
    product: linux
    service: auditd
detection:
    selection:
        type: 'SYSCALL'
        key:
          - 'etc_modify_auditconfig'
          - 'etc_modify_libauditconfig'
          - 'etc_modify_audispconfig'
    condition: selection
fields:
    - exe
    - comm
    - key
falsepositives:
    - Legitimate administrative activity
level: high
