name: Rebuild uberAgent ESA rules based on sigma rules

on:
  workflow_dispatch:
  schedule:
    - cron:  '13 4 * * *'
      displayName: Daily nightly build at 04:13
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install markdown
          pip install markdown-link-attr-modifier
      - name: build
        working-directory: sigma/tools
        run: |
          python sigma/sigmac.py -I --target uberagent -r ../rules/
      - name: push
        uses: actions-x/commit@v6
        with:
          files: uberAgent-ESA-am-sigma-low.conf, uberAgent-ESA-am-sigma-medium.conf, uberAgent-ESA-am-sigma-high.conf, uberAgent-ESA-am-sigma-critical.conf
