title: Executable and Files creation by Office Applications
description: This rule will monitor executable and script file creation by office applications. Please add more file extentions or magic bytes to the logic of your choice.  
references:
    - https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/
    - https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/main/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml
author: "Vadim Khrykov (ThreatIntel), Cyb3rEng (Rule)"
tags:
    - attack.t1204.002
    - attack.t1047
    - attack.t1218.010
    - attack.execution
    - attack.defence_evasion
status: experimental
Date: 2021/08/23
logsource:
  product: Windows
  category: process_creation
detection:
  #useful_information: Please add more file extentions and magic bytes to the logic of your choice. 
  selection1:
    EventType:
      - FileCreate
      - FileRename
  selection2:
    Image|endswith:
      - 'winword.exe'
      - 'excel.exe'
      - 'powerpnt.exe'
  selection3:
    FileName|endswith:
    - ".exe"
    - ".dll"
    - ".ocx"
    - ".com"
    - ".ps1"
    - ".vbs"
    - ".sys"
    - ".bat"
    - ".scr"
    - ".proj"
  selection4:
    FileMagicBytes|startswith:
    - "4D5A"
  condition: selection1 AND selection2 AND (selection3 OR selection4)
falsepositives:
- Unknown
level: high
