title: Start of NT Virtual DOS Machine
id: 16905e21-66ee-42fe-b256-1318ada2d770
status: experimental
description: Ntvdm.exe allows the execution of 16-bit Windows applications on 32-bit Windows operating systems, as well as the execution of both 16-bit and 32-bit DOS applications
author: frack113
references:
    - https://app.any.run/tasks/93fe92fa-8b2b-4d92-8c09-a841aed2e793/
    - https://docs.microsoft.com/en-us/windows/compatibility/ntvdm-and-16-bit-app-support
date: 2022/07/16
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: '\ntvdm.exe'
    condition: selection
falsepositives:
    - Legitimate use 
level: medium
tags:
    - attack.defense_evasion

